# Generated by Django 2.2.1 on 2019-07-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='记账本id')),
                ('time', models.DateTimeField(db_column='time', verbose_name='记账时间')),
                ('amount', models.IntegerField(db_column='amount', verbose_name='金额(分)')),
                ('memo', models.CharField(db_column='memo', max_length=100, verbose_name='备注')),
            ],
            options={
                'verbose_name': '记账表',
                'db_table': 'bill',
                'managed': False,
            },
        ),
    ]
