# Generated by Django 2.2.1 on 2019-06-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b2c_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='TbAddress',
        ),
        migrations.DeleteModel(
            name='TbAdmin',
        ),
        migrations.DeleteModel(
            name='TbBuyer',
        ),
        migrations.DeleteModel(
            name='TbCategory',
        ),
        migrations.DeleteModel(
            name='TbLogistics',
        ),
        migrations.DeleteModel(
            name='TbOrders',
        ),
        migrations.DeleteModel(
            name='TbOrdersitem',
        ),
        migrations.DeleteModel(
            name='TbProduct',
        ),
        migrations.DeleteModel(
            name='TbProductcar',
        ),
        migrations.DeleteModel(
            name='TbSeller',
        ),
        migrations.DeleteModel(
            name='TbShopcar',
        ),
        migrations.DeleteModel(
            name='TbStore',
        ),
    ]
